Repository ergoplatform/ergo, pull requests merged in 2018-02, with the labels that each got.

#163 Fix for #162 : offline generation does not start
  src/main/scala/org/ergoplatform/ErgoApp.scala
  src/main/scala/org/ergoplatform/local/ErgoMiner.scala
Labels: in progress

#164 update for new CORS settings
  build.sbt
  lock.sbt
  src/test/scala/org/ergoplatform/api/routes/InfoRoutesSpec.scala
  src/test/scala/org/ergoplatform/api/routes/TransactionApiRouteSpec.scala
Labels: in progress

#170 Correct node name in InfoRoute
  src/main/scala/org/ergoplatform/ErgoApp.scala
  src/main/scala/org/ergoplatform/api/routes/InfoRoute.scala
  src/test/scala/org/ergoplatform/api/routes/InfoRoutesSpec.scala
Labels: in progress, wip

#169 Repaired powType config setting
  src/main/scala/org/ergoplatform/mining/FakePowScheme.scala
  src/main/scala/org/ergoplatform/mining/PoWScheme.scala
  src/main/scala/org/ergoplatform/settings/ErgoSettings.scala
  src/main/scala/org/ergoplatform/settings/PowSchemeReader.scala
Labels: in progress

#189 Candidate block creation errors
  build.sbt
  lock.sbt
  src/main/resources/application.conf
  src/main/scala/org/ergoplatform/ErgoApp.scala
  src/main/scala/org/ergoplatform/api/routes/InfoRoute.scala
  src/main/scala/org/ergoplatform/crypto/Equihash.scala
  src/main/scala/org/ergoplatform/local/ErgoLocalInterface.scala
  src/main/scala/org/ergoplatform/local/ErgoMiner.scala
  src/main/scala/org/ergoplatform/local/ErgoStatsCollector.scala
  src/main/scala/org/ergoplatform/mining/PoWScheme.scala
  src/main/scala/org/ergoplatform/nodeView/state/UtxoState.scala
  src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala
  src/test/scala/org/ergoplatform/api/routes/InfoRoutesSpec.scala
  src/test/scala/org/ergoplatform/nodeView/state/UtxoStateSpecification.scala
Labels: wip
