Repository ergoplatform/ergo, pull requests merged in 2019-12, with the labels that each got.

#976 Add initial version of ergo-installer script
  README.md
  ergo-installer.sh
Labels: S-ready-for-merge

#985 Cross-build(scala 2.11) for ergoWallet; Automate publishing; Remove sbt-lock;
  .travis.yml
  build.sbt
  ci/pubring.asc
  ci/secring.asc.enc
  ergo-wallet/build.sbt
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/mnemonic/WordList.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/secrets/JsonSecretStorage.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/interpreter/ErgoUnsafeProverSpec.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/secrets/SecretDerivationSpec.scala
  lock.sbt
  project/plugins.sbt
Labels: S-ready-for-merge

#1016 fix for empty gitHeadCommit
  build.sbt
Labels: S-ready-for-merge

#1014 Fix ergo-installer.sh
  ergo-installer.sh
Labels: S-ready-for-merge

#1011 Use LDBVersionedStore for wallet also
  avldb/benchmarks/src/main/scala/scorex/crypto/authds/benchmarks/AVLTreeBatchPerformance.scala
  avldb/benchmarks/src/main/scala/scorex/crypto/authds/benchmarks/Helper.scala
  avldb/build.sbt
  avldb/src/main/scala/scorex/crypto/authds/avltree/batch/ProxyInternalProverNode.scala
  avldb/src/main/scala/scorex/crypto/authds/avltree/batch/VersionedLDBAVLStorage.scala
  avldb/src/main/scala/scorex/db/KVStore.scala
  avldb/src/main/scala/scorex/db/LDBFactory.scala
  avldb/src/main/scala/scorex/db/LDBKVStore.scala
  avldb/src/main/scala/scorex/db/LDBVersionedStore.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/AVLStorageWithPersistentProverSpec.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/IODBStorageSpecification.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/VersionedLDBAVLStorageSpecification.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/VersionedLDBAVLStorageStatefulSpecification.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/benchmark/BatchingBenchmark.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/benchmark/LDBVersionedStoreBenchmark.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/benchmark/OOMTest.scala
  avldb/src/test/scala/scorex/crypto/authds/avltree/batch/helpers/TestHelper.scala
  benchmarks/src/test/resources/logback-bench.xml
  benchmarks/src/test/scala/org/ergoplatform/db/LDBStoreBench.scala
  benchmarks/src/test/scala/org/ergoplatform/db/VLDBStoreRollbackBench.scala
  build.sbt
  src/main/scala/org/ergoplatform/db/KVStore.scala
  src/main/scala/org/ergoplatform/db/LDBFactory.scala
  src/main/scala/org/ergoplatform/db/VersionedLDBKVStore.scala
  src/main/scala/org/ergoplatform/nodeView/ErgoNodeViewHolder.scala
  src/main/scala/org/ergoplatform/nodeView/history/ErgoHistory.scala
  src/main/scala/org/ergoplatform/nodeView/history/storage/HistoryStorage.scala
  src/main/scala/org/ergoplatform/nodeView/history/storage/modifierprocessors/FullBlockProcessor.scala
  src/main/scala/org/ergoplatform/nodeView/state/BoxHolder.scala
  src/main/scala/org/ergoplatform/nodeView/state/DigestState.scala
  src/main/scala/org/ergoplatform/nodeView/state/ErgoStateReader.scala
  src/main/scala/org/ergoplatform/nodeView/state/UtxoState.scala
  src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/persistence/RegistryOps.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/persistence/WalletRegistry.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/persistence/WalletStorage.scala
  src/main/scala/org/ergoplatform/settings/Algos.scala
  src/main/scala/org/ergoplatform/utils/FileUtils.scala
  src/test/resources/logback-test.xml
  src/test/scala/org/ergoplatform/db/DBSpec.scala
  src/test/scala/org/ergoplatform/db/LDBKVStoreSpec.scala
  src/test/scala/org/ergoplatform/db/LegacyDbEqualitySpec.scala
  src/test/scala/org/ergoplatform/db/VersionedLDBKVStoreSpec.scala
  src/test/scala/org/ergoplatform/nodeView/state/wrapped/WrappedUtxoState.scala
  src/test/scala/org/ergoplatform/nodeView/viewholder/ErgoNodeViewHolderSpec.scala
  src/test/scala/org/ergoplatform/nodeView/wallet/persistence/RegistryOpsSpec.scala
  src/test/scala/org/ergoplatform/nodeView/wallet/persistence/WalletRegistrySpec.scala
  src/test/scala/org/ergoplatform/nodeView/wallet/persistence/WalletStorageSpec.scala
  src/test/scala/org/ergoplatform/sanity/ErgoSanityDigest.scala
  src/test/scala/org/ergoplatform/utils/Stubs.scala
Labels: S-wip

#997 it2:test for light regimes
  src/it2/scala/org/ergoplatform/it2/TestDigestStateOnMainNetSpec.scala
  src/it2/scala/org/ergoplatform/it2/TestDigestStateWithPruningOnMainNetSpec.scala
Labels: A-tests, S-ready-for-merge
