Repository ergoplatform/ergo, pull requests merged in 2020-12, with the labels that each got.

#1239 Unconfirmed transactions added to /scan/unspent
  src/main/resources/api/openapi.yaml
  src/main/scala/org/ergoplatform/http/api/ScanApiRoute.scala
  src/main/scala/org/ergoplatform/http/api/TransactionsApiRoute.scala
  src/main/scala/org/ergoplatform/http/api/UtxoApiRoute.scala
  src/main/scala/org/ergoplatform/http/api/WalletApiRoute.scala
  src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPool.scala
  src/main/scala/org/ergoplatform/nodeView/mempool/ErgoMemPoolReader.scala
  src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/ErgoWalletActor.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/ErgoWalletReader.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/WalletScanLogic.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/persistence/OffChainRegistry.scala
  src/test/scala/org/ergoplatform/http/routes/ScanApiRouteSpec.scala
  src/test/scala/org/ergoplatform/http/routes/UtxoApiRouteSpec.scala
  src/test/scala/org/ergoplatform/local/MempoolAuditorSpec.scala
  src/test/scala/org/ergoplatform/utils/Stubs.scala
Labels: S-ready-for-merge, S-ready-for-review

#1148 More expiration tests
  papers/yellow/modifiersValidation.tex
  src/main/scala/org/ergoplatform/http/api/TransactionsApiRoute.scala
  src/main/scala/org/ergoplatform/http/api/UtxoApiRoute.scala
  src/main/scala/org/ergoplatform/http/api/WalletApiRoute.scala
  src/main/scala/org/ergoplatform/modifiers/mempool/ErgoBoxSerializer.scala
  src/main/scala/org/ergoplatform/modifiers/mempool/ErgoTransaction.scala
  src/main/scala/org/ergoplatform/nodeView/state/DigestState.scala
  src/main/scala/org/ergoplatform/nodeView/state/ErgoState.scala
  src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala
  src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/ErgoWalletActor.scala
  src/main/scala/org/ergoplatform/settings/ErgoValidationSettings.scala
  src/main/scala/org/ergoplatform/settings/ValidationRules.scala
  src/test/scala/org/ergoplatform/http/routes/UtxoApiRouteSpec.scala
  src/test/scala/org/ergoplatform/modifiers/mempool/ErgoTransactionSpec.scala
  src/test/scala/org/ergoplatform/modifiers/mempool/ExpirationSpecification.scala
  src/test/scala/org/ergoplatform/nodeView/wallet/ErgoWalletSpec.scala
  src/test/scala/org/ergoplatform/sanity/ErgoSanity.scala
  src/test/scala/org/ergoplatform/serialization/ErgoBoxSerializerSpec.scala
  src/test/scala/org/ergoplatform/serialization/SerializationTests.scala
  src/test/scala/org/ergoplatform/utils/generators/ValidBlocksGenerators.scala
Labels: S-ready-for-merge

#1237 v4.0.0 with outsourceable PoW
  papers/yellow/pow/ErgoPow.tex
  src/main/scala/org/ergoplatform/mining/AutolykosPowScheme.scala
  src/main/scala/org/ergoplatform/mining/AutolykosSolution.scala
  src/main/scala/org/ergoplatform/mining/WorkMessage.scala
  src/main/scala/org/ergoplatform/mining/mining.scala
  src/test/scala/org/ergoplatform/mining/AutolykosPowSchemeSpec.scala
  src/test/scala/org/ergoplatform/utils/Stubs.scala
Labels: S-ready-for-merge, S-ready-for-review

#1251 Pass activated version parameters to sigma
  build.sbt
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/ErgoBoxSerializer.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/interpreter/ErgoProvingInterpreter.scala
  src/main/scala/org/ergoplatform/modifiers/mempool/ErgoTransaction.scala
  src/main/scala/org/ergoplatform/nodeView/ErgoContext.scala
  src/main/scala/org/ergoplatform/nodeView/state/ErgoStateContext.scala
  src/test/resources/execute-script.json
Labels: A-consensus, S-wip
