Repository ergoplatform/ergo, pull requests merged in 2020-05, with the labels that each got.

#1101 Build transaction with token burning
  .gitignore
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/AssetUtils.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/BoxSelector.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/ReplaceCompactCollectBoxSelector.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/TrackedBox.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/package.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/transactions/TransactionBuilder.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/AssetUtilsSpec.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/transactions/TransactionBuilderSpec.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/utils/WalletTestHelpers.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/BalancesSnapshot.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/ErgoWalletActor.scala
  src/test/scala/org/ergoplatform/utils/WalletTestOps.scala
Labels: S-ready-for-review

#1107 Do not initialize miner if mining = false
  src/main/scala/org/ergoplatform/ErgoApp.scala
  src/main/scala/org/ergoplatform/http/api/MiningApiRoute.scala
  src/main/scala/org/ergoplatform/local/ErgoMiner.scala
Labels: C-bug, S-ready-for-merge

#1108 Obsolete TransactionGenerator removed
  src/main/resources/node1/application.conf
  src/main/resources/node2/application.conf
  src/main/resources/reference.conf
  src/main/resources/testnet.conf
  src/main/scala/org/ergoplatform/ErgoApp.scala
  src/main/scala/org/ergoplatform/local/TransactionGenerator.scala
  src/main/scala/org/ergoplatform/settings/ErgoSettings.scala
  src/main/scala/org/ergoplatform/settings/TestingSettings.scala
  src/test/scala/org/ergoplatform/local/TransactionGeneratorSpec.scala
  src/test/scala/org/ergoplatform/tools/ChainGenerator.scala
  src/test/scala/org/ergoplatform/utils/HistoryTestHelpers.scala
  src/test/scala/org/ergoplatform/utils/Stubs.scala
Labels: S-ready-for-merge

#1104 Complexity limit raised to 250K
  src/main/resources/api/openapi.yaml
  src/main/resources/reference.conf
  src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala
  src/main/scala/org/ergoplatform/settings/Constants.scala
  src/test/scala/org/ergoplatform/mining/ErgoMinerSpec.scala
  src/test/scala/org/ergoplatform/nodeView/state/UtxoStateSpecification.scala
  src/test/scala/org/ergoplatform/settings/ErgoSettingsSpecification.scala
  src/test/scala/org/ergoplatform/tools/ChainGenerator.scala
  src/test/scala/org/ergoplatform/utils/HistoryTestHelpers.scala
  src/test/scala/org/ergoplatform/utils/Stubs.scala
Labels: C-feature, S-ready-for-merge

#1109 Candidate for version 3.2.4
  .gitignore
  .travis.yml
  ci/publish_release_gpg2.sh
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/AssetUtils.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/BoxSelector.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/DefaultBoxSelector.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/ReplaceCompactCollectBoxSelector.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/TrackedBox.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/interpreter/ErgoProvingInterpreter.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/package.scala
  ergo-wallet/src/main/scala/org/ergoplatform/wallet/transactions/TransactionBuilder.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/AssetUtilsSpec.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/transactions/TransactionBuilderSpec.scala
  ergo-wallet/src/test/scala/org/ergoplatform/wallet/utils/WalletTestHelpers.scala
  src/main/resources/api/openapi.yaml
  src/main/resources/node1/application.conf
  src/main/resources/node2/application.conf
  src/main/resources/reference.conf
  src/main/resources/testnet.conf
  src/main/scala/org/ergoplatform/ErgoApp.scala
  src/main/scala/org/ergoplatform/http/api/MiningApiRoute.scala
  src/main/scala/org/ergoplatform/local/ErgoMiner.scala
  src/main/scala/org/ergoplatform/local/TransactionGenerator.scala
  src/main/scala/org/ergoplatform/nodeView/state/UtxoStateReader.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/BalancesSnapshot.scala
  src/main/scala/org/ergoplatform/nodeView/wallet/ErgoWalletActor.scala
  src/main/scala/org/ergoplatform/settings/Constants.scala
  src/main/scala/org/ergoplatform/settings/ErgoSettings.scala
  src/main/scala/org/ergoplatform/settings/TestingSettings.scala
  src/test/scala/org/ergoplatform/local/TransactionGeneratorSpec.scala
  src/test/scala/org/ergoplatform/mining/ErgoMinerSpec.scala
  src/test/scala/org/ergoplatform/nodeView/state/UtxoStateSpecification.scala
  src/test/scala/org/ergoplatform/settings/ErgoSettingsSpecification.scala
  src/test/scala/org/ergoplatform/tools/ChainGenerator.scala
  src/test/scala/org/ergoplatform/utils/HistoryTestHelpers.scala
  src/test/scala/org/ergoplatform/utils/Stubs.scala
  src/test/scala/org/ergoplatform/utils/WalletTestOps.scala
Labels: S-ready-for-merge
